### ISSUE TITLE
Inquiry Regarding Using Repo with BiGym

### ISSUE THREAD

**Issue by helen9975** [robobase-org/robobase#3]
Hi,

Thanks for opensourcing this repo. I was wondering if the bigym documentation could be added? I tried adapting the current commands in readme for training RLBench for BiGym, and came across the following error. Any ideas why?

Thanks!

Here's the error log:

> python3 train.py method=drqv2 env=bigym/reach_target_dual env.episode_length=100 demos=10 pixels=true
> [2024-11-12 23:19:01,552][OpenGL.acceleratesupport][INFO] - No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
> [2024-11-12 23:19:01,607][absl][INFO] - MUJOCO_GL=egl, attempting to import specified OpenGL backend.
> [2024-11-12 23:19:01,612][absl][INFO] - MuJoCo library version is: 3.1.5
> workspace: /home/helen/Documents/bimanual/robobase/exp_local/2024.11.12/231900_demos=10,env.episode_length=100,env=bigym/reach_target_dual,method=drqv2,pixels=true
> [2024-11-12 23:19:01,771][root][INFO] - Start to load demos.
> Process Process-2:
> Traceback (most recent call last):
>   File "/home/helen/miniconda3/envs/bigym/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
>     self.run()
>   File "/home/helen/miniconda3/envs/bigym/lib/python3.10/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/helen/Documents/bimanual/robobase/robobase/envs/bigym.py", line 186, in _get_demo_fn
>     env = self._create_env(cfg)
>   File "/home/helen/Documents/bimanual/robobase/robobase/envs/bigym.py", line 147, in _create_env
>     return bigym_class(
>   File "/home/helen/miniconda3/envs/bigym/lib/python3.10/site-packages/bigym/bigym_env.py", line 131, in __init__
>     self._initialize_renderers()
>   File "/home/helen/miniconda3/envs/bigym/lib/python3.10/site-packages/bigym/bigym_env.py", line 215, in _initialize_renderers
>     self.obs_renderers[resolution] = mujoco.Renderer(
>   File "/home/helen/miniconda3/envs/bigym/lib/python3.10/site-packages/mujoco/renderer.py", line 83, in __init__
>     self._gl_context = gl_context.GLContext(width, height)
>   File "/home/helen/miniconda3/envs/bigym/lib/python3.10/site-packages/mujoco/egl/__init__.py", line 109, in __init__
>     self._context = EGL.eglCreateContext(
>   File "/home/helen/miniconda3/envs/bigym/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
>     return self( *args, **named )
>   File "/home/helen/miniconda3/envs/bigym/lib/python3.10/site-packages/OpenGL/error.py", line 230, in glCheckError
>     raise self._errorClass(
> OpenGL.raw.EGL._errors.EGLError: EGLError(
>         err = EGL_BAD_ALLOC,
>         baseOperation = eglCreateContext,
>         cArguments = (
>                 <OpenGL._opaque.EGLDisplay_pointer object at 0x7c1f13c0aac0>,
>                 <OpenGL._opaque.EGLConfig_pointer object at 0x7c1ff21ec340>,
>                 <OpenGL._opaque.EGLContext_pointer object at 0x7c1f13c091c0>,
>                 None,
>         ),
>         result = <OpenGL._opaque.EGLContext_pointer object at 0x7c1ff24e5840>
> )
> Exception ignored in: <function GLContext.__del__ at 0x7c1f13c67370>
> Traceback (most recent call last):
>   File "/home/helen/miniconda3/envs/bigym/lib/python3.10/site-packages/mujoco/egl/__init__.py", line 131, in __del__
>     self.free()
>   File "/home/helen/miniconda3/envs/bigym/lib/python3.10/site-packages/mujoco/egl/__init__.py", line 121, in free
>     if self._context:
> AttributeError: 'GLContext' object has no attribute '_context'
> Exception ignored in: <function Renderer.__del__ at 0x7c1f13c67d00>
> Traceback (most recent call last):
>   File "/home/helen/miniconda3/envs/bigym/lib/python3.10/site-packages/mujoco/renderer.py", line 335, in __del__
>     self.close()
>   File "/home/helen/miniconda3/envs/bigym/lib/python3.10/site-packages/mujoco/renderer.py", line 323, in close
>     if self._mjr_context:
> AttributeError: 'Renderer' object has no attribute '_mjr_context'
> Error executing job with overrides: ['method=drqv2', 'env=bigym/reach_target_dual', 'env.episode_length=100', 'demos=10', 'pixels=true']
> Traceback (most recent call last):
>   File "/home/helen/Documents/bimanual/robobase/train.py", line 14, in main
>     workspace = Workspace(cfg)
>   File "/home/helen/Documents/bimanual/robobase/robobase/workspace.py", line 159, in __init__
>     self.env_factory.collect_or_fetch_demos(cfg, num_demos)
>   File "/home/helen/Documents/bimanual/robobase/robobase/envs/bigym.py", line 219, in collect_or_fetch_demos
>     demos = mp_list[0]
>   File "<string>", line 2, in __getitem__
>   File "/home/helen/miniconda3/envs/bigym/lib/python3.10/multiprocessing/managers.py", line 833, in _callmethod
>     raise convert_to_error(kind, result)
> IndexError: list index out of range
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by lingxiao-guo** [comment]
Hi, @helen9975, have you solved this problem?

**Comment by younggyoseo** [comment]
You might want to check if `DISPLAY` env variable is properly set. Sometimes you should also set `DISPLAY` variable for your machines. From my experience, BiGym rendering works without a problem in most machines. But sometimes I had to set X config as in https://github.com/stepjam/RLBench and then set a DISPLAY variable.

**Comment by helen9975** [comment]
Thanks, seems that the error went away after a while, perhaps due to a restart.
